# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1dd95e378f8fd01d5429180a5d9084d349659eaef4dfc12d4d3b6367c47fab2fee4fd66f33d9ec76f7c4d239fb19a28dd410503c964dba473c64388dd9b4dade

test:
  secret_key_base: f257ac9b2be9858c8f544566d42e2f619540300b405cee47a3a0c638a7c30460ff32ae27b1e95bef0d9c6cd3adac97bc47ce4b9781beebab658a12a1c13b6602

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
